package scan_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/jasonflaherty/foxhole/internal/scan"
)

func TestParseCargoLock(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	content := `# This file is automatically @generated by Cargo.
[[package]]
name = "serde"
version = "1.0.195"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "libc"
version = "0.2.152"
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.lock"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	pkgs, err := scan.NewFilesystemScanner().Scan(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 2 {
		t.Fatalf("packages = %#v", pkgs)
	}
	if pkgs[0].Ecosystem != "crates.io" {
		t.Fatalf("ecosystem = %s", pkgs[0].Ecosystem)
	}
}
